name:                imp-haskell
version:             0.1.0.0
github:              "githubuser/imp-haskell"
license:             BSD3
author:              "zl38"
maintainer:          "zl38@illinois.edu"
copyright:           "2020 zl38"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rod-lin/imp-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- parsec == 3.1.14.0
- containers == 0.6.2.1
- mtl == 2.2.2

library:
  source-dirs: src

executables:
  imp-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - imp-haskell

tests:
  imp-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - imp-haskell
    - hspec
    - QuickCheck
